uploads = []
generated = []

[[outputs]]
id = "E30TQj1ErgEY0OppLv6Af"
uri = "file://hecaro-digital.tar.gz"
type = "unspecified"
title = "hecaro-digital.tar.gz — Quellcode (ohne node_modules / .next)"

[[outputs]]
id = "6Cvlb76I_4kuy_u0BJm1A"
uri = "file://hecaro-digital.zip"
type = "unspecified"
title = "HECARO Digital – Projekt-Download"
